### ISSUE TITLE
[PHP Warning] Invalid argument supplied for foreach() on line 951

### ISSUE THREAD

**Issue by lyovav** [undeflabs/UASECO#23]
Version 0.9.5 build 2017-06-08 
[PHP Warning] Invalid argument supplied for foreach() on line 951 in file /opt/total_lol_tm4/UASECO-0.9.5_2017-06-08/plugins/plugin.modescript_handler.php

more on the link
game.ber.te.ua/logs.tar.gz

https://1drv.ms/u/s!Aq_8ScOZC7u_mUirnY1V_LSXuaji

**Comment by undeflabs** [comment]
Strange that this error happens after 23 hours running without this error... Also strange is, that I only take that variable from the ModeScript, so maybe the ModeScript has not sent that array?!?! Or it's related to FreeBSD which you are running (because nobody else has reported this yet)...

Anyway, added a test for the availability of that array.
