### ISSUE TITLE
rocordeyepiece and other links in HUD not working

### ISSUE THREAD

**Issue by BestNoob** [undeflabs/UASECO#41]
rocordeyepiece and other links in HUD not working

**Comment by undeflabs** [comment]
Which exactly? Do you use the current github branch?

**Comment by BestNoob** [comment]
All ecternals not working, nope after the databse problem i switched back to stable.

**Comment by undeflabs** [comment]
Please provide more details which links do you mean. Links from buttons you can click on or links from images that will be loaded into the HUD? Reopen if the problem still is existend.

**Comment by BestNoob** [comment]
This are only a few links not working, like i said before; all external links seems to be broken.

![all_external_links_broken_uaseco 001](https://user-images.githubusercontent.com/9570592/59158614-f4f9b100-8abc-11e9-8b55-5a831df7465f.jpg)
![all_external_links_broken_uaseco 002](https://user-images.githubusercontent.com/9570592/59158615-f4f9b100-8abc-11e9-8606-1ccd7c7342bc.jpg)
![all_external_links_broken_uaseco 003](https://user-images.githubusercontent.com/9570592/59158616-f4f9b100-8abc-11e9-932c-3fd76a49e307.jpg)
![all_external_links_broken_uaseco 004](https://user-images.githubusercontent.com/9570592/59158617-f4f9b100-8abc-11e9-9cbc-fc63cef11121.jpg)
![all_external_links_broken_uaseco 005](https://user-images.githubusercontent.com/9570592/59158618-f5924780-8abc-11e9-8506-bf92155df6de.jpg)
![all_external_links_broken_uaseco 006](https://user-images.githubusercontent.com/9570592/59158619-f5924780-8abc-11e9-9edc-780a08c768af.jpg)

**Comment by undeflabs** [comment]
The "about" link from Records-Eyepiece has been fixed (and all external links from other plugins too, because it was in the WindowClass).

The link to dedimania.net ("MORE INFO ON DEDIMANIA.NET) was working, no changes made.

AddFavorite-Button links was working, no changes made. Donation links at AddFavorite-Manialink has been fixed.

No other links found which are not working, if you still have some, feel free to add them here again.
